name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps: 
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependecies
        run: pnpm install --frozen-lockfile

  lint:
    needs: [install]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependecies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run eslint
  build:
    needs: [install , lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependecies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  test:
    needs: [install ,lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependecies
        run: pnpm install --frozen-lockfile  
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist              
      - name: Test
        run: pnpm run test 
  e2e-test:
    needs: [install ,lint,build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependecies
        run: pnpm install --frozen-lockfile  
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist 
      - name: E2E test
        uses: cypress-io/github-action@v6
        with: 
          command: pnpm run test:e2e
          start: pnpm run start-test
          wait-on: http://localhost:5000





  # deploy:
  #   needs: [test, e2e-test]
  #   runs-on: ubuntu-latest
      # - name: Deploy to Heroku
      #   if: ${{ github.event_name == 'push' }}
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: ${{secrets.HEROKU_APP}}
      #     heroku_email: ${{secrets.HEROKU_API_EMAIL}}
      #     healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
      #     rollbackonhealthcheckfailed: true
